# Generated by Django 4.2.25 on 2025-10-22 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_bonlivraison_alter_achat_date_achat_alter_achat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('canceled', 'Annulée')], default='draft', max_length=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bon_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='API.bonlivraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='API.client')),
            ],
            options={
                'ordering': ['-date_emission', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('prixU_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
            ],
        ),
    ]
