# Generated by Django 4.2.25 on 2025-10-22 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_facture_lignefacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('canceled', 'Annulé')], default='draft', max_length=10)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('source', models.CharField(choices=[('BL', 'Bon de livraison'), ('BC', 'Bon de commande'), ('ACHAT', 'Vente simple'), ('INV', 'Inventaire'), ('CORR', 'Correction'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('ref_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='API.produit')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.IntegerField()),
                ('snapshot_qty', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.inventorysession')),
            ],
        ),
    ]
