# Generated by Django 4.2.25 on 2025-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_inventorysession_stockmove_inventoryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Code-barres'),
        ),
    ]
