# Generated by Django 4.2.25 on 2025-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_fill_code_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(default=0, max_length=64, unique=True, verbose_name='Code-barres'),
            preserve_default=False,
        ),
    ]
