# Generated by Rovo Dev to add missing date_expiration on Produit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_produit_code_barre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(null=True, blank=True, verbose_name="Date d'expiration"),
        ),
    ]
