# Generated by Rovo Dev to move date_expiration from Produit to Achat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_produit_date_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='date_expiration',
        ),
        migrations.AddField(
            model_name='achat',
            name='date_expiration',
            field=models.DateField(null=True, blank=True, verbose_name="Date d'expiration"),
        ),
    ]
