# Generated by Django 5.2.7 on 2025-10-23 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_move_date_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_paiement', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('transfer', 'Virement'), ('credit', 'Crédit')], default='cash', max_length=10)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('completed', 'Terminée'), ('canceled', 'Annulée')], default='draft', max_length=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observations', models.TextField(blank=True)),
                ('bon_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='API.bonlivraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='API.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='API.facture')),
            ],
            options={
                'ordering': ['-date_vente', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('prixU_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.vente')),
            ],
        ),
    ]
