# Generated by Django 5.2.7 on 2025-10-23 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_vente_lignevente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO 4217 (ex: USD, EUR, MAD)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Nom de la devise', max_length=50)),
                ('symbol', models.CharField(help_text='Symbole (ex: $, €, DH)', max_length=5)),
                ('is_default', models.BooleanField(default=False, help_text='Devise par défaut du système')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='exchange_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Taux de change figé au moment de la vente', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Devise du prix unitaire (héritée du produit)', null=True, on_delete=django.db.models.deletion.PROTECT, to='API.currency'),
        ),
        migrations.AddField(
            model_name='produit',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Devise du prix (si vide, utilise la devise par défaut)', null=True, on_delete=django.db.models.deletion.PROTECT, to='API.currency'),
        ),
        migrations.AddField(
            model_name='vente',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Devise de la vente (si vide, utilise la devise par défaut)', null=True, on_delete=django.db.models.deletion.PROTECT, to='API.currency'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Taux de change (1 from_currency = rate to_currency)', max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='API.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='API.currency')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
