# Generated by Django 5.2.7 on 2025-10-23 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_currency_vente_exchange_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['reference'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dimensions (LxlxH)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Produit actif'),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=10, help_text='Niveau de stock déclenchant une alerte', verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_critique',
            field=models.IntegerField(default=5, help_text='Niveau de stock critique (urgent)', verbose_name='Seuil critique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube')], default='piece', max_length=10, verbose_name='Unité de mesure'),
        ),
        migrations.AddField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixU',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité en stock'),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('couleur', models.CharField(default='#007bff', help_text="Couleur d'affichage (hex)", max_length=7)),
                ('icone', models.CharField(default='fa-cube', help_text='Icône Font Awesome', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Catégorie parent pour hiérarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='API.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=0, help_text='Catégorie du produit', on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='API.categorie'),
            preserve_default=False,
        ),
    ]
