# Generated by Django 4.2.25 on 2025-10-24 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0012_alter_produit_options_produit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryline',
            name='counted_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure du comptage', null=True),
        ),
        migrations.AddField(
            model_name='inventoryline',
            name='counted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a compté ce produit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines_counted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='completed_products',
            field=models.IntegerField(default=0, help_text='Nombre de produits déjà comptés'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pourcentage de completion de l'inventaire", max_digits=5),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a créé la session d'inventaire", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='total_products',
            field=models.IntegerField(default=0, help_text='Nombre total de produits à inventorier'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a validé l'inventaire", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryline',
            name='counted_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('validated', 'Validé'), ('canceled', 'Annulé')], default='draft', max_length=15),
        ),
    ]
