# Generated by Django 4.2.25 on 2025-10-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_warehouse_stockmove_warehouse_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
