# Generated by Rovo Dev to add missing prix_achat on Achat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='prix_achat',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
    ]
