# Generated by Django 4.2.25 on 2025-10-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_add_prix_achat_to_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Entrepôt de sortie pour cette vente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='API.warehouse'),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_default_for', to='API.warehouse')),
            ],
        ),
    ]
