# Generated by Django 4.2.25 on 2025-10-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_vente_warehouse_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_default_currency_for', to='API.currency'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='source',
            field=models.CharField(choices=[('BL', 'Bon de livraison'), ('BC', 'Bon de commande'), ('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('INV', 'Inventaire'), ('CORR', 'Correction'), ('PERTE', 'Perte'), ('CASSE', 'Casse'), ('EXP', 'Expiration'), ('TRANS', 'Transfert'), ('SAMPLE', 'Échantillon'), ('DON', 'Don'), ('CONS', 'Consommation interne'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10),
        ),
    ]
