# Generated by Django 4.2.25 on 2025-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_systemconfig_default_currency_alter_stockmove_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='auto_print_ticket',
            field=models.BooleanField(default=False, help_text='Générer automatiquement le ticket de caisse'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ticket_company_address',
            field=models.TextField(blank=True, help_text="Adresse de l'entreprise"),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ticket_company_name',
            field=models.CharField(blank=True, help_text="Nom de l'entreprise à afficher sur le ticket", max_length=200),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ticket_company_phone',
            field=models.CharField(blank=True, help_text="Téléphone de l'entreprise", max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ticket_footer_message',
            field=models.TextField(blank=True, help_text='Message à afficher au pied du ticket (merci, mentions légales, etc.)'),
        ),
    ]
