# Generated by Django 4.2.25 on 2025-10-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_systemconfig_auto_print_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='produits',
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.fournisseur'),
        ),
        migrations.AddField(
            model_name='achat',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Entrepôt de destination pour cet achat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='API.warehouse'),
        ),
    ]
