# Generated by Django 4.2.25 on 2025-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_remove_achat_client_remove_client_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='source',
            field=models.CharField(choices=[('BL', 'Bon de livraison'), ('BC', 'Bon de commande'), ('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('INV', 'Inventaire'), ('CORR', 'Correction'), ('PERTE', 'Perte'), ('CASSE', 'Casse'), ('EXP', 'Expiration'), ('TRANS', 'Transfert'), ('SAMPLE', 'Échantillon'), ('DON', 'Don'), ('CONS', 'Consommation interne'), ('RETOUR', 'Retour fournisseur'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15),
        ),
    ]
