# Generated by Django 4.2.25 on 2025-10-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_alter_stockmove_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du type de prix (ex: DETAIL, GROSS, PROMO)', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Libellé du type de prix', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du type de prix')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_default', models.BooleanField(default=False, help_text='Type de prix par défaut')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de prix',
                'verbose_name_plural': 'Types de prix',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Montant du prix pour ce type', max_digits=10, verbose_name='Prix')),
                ('quantite_min', models.IntegerField(default=1, help_text='Quantité minimum pour appliquer ce prix', verbose_name='Quantité minimum')),
                ('date_debut', models.DateField(blank=True, help_text='Date de début de validité (laisser vide si permanent)', null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de validité (laisser vide si permanent)', null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Prix actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Devise du prix (si vide, hérite de la devise du produit)', null=True, on_delete=django.db.models.deletion.PROTECT, to='API.currency')),
                ('produit', models.ForeignKey(help_text='Produit concerné', on_delete=django.db.models.deletion.CASCADE, related_name='prix_multiples', to='API.produit')),
                ('type_prix', models.ForeignKey(help_text='Type de prix (détaillant, grossiste, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='prix', to='API.typeprix')),
            ],
            options={
                'verbose_name': 'Prix produit',
                'verbose_name_plural': 'Prix produits',
                'ordering': ['produit', 'type_prix__ordre'],
                'unique_together': {('produit', 'type_prix')},
            },
        ),
    ]
