# Generated by Django 4.2.25 on 2025-10-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_typeprix_prixproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', help_text="Langue de l'interface", max_length=5),
        ),
    ]
