# Generated by Django 4.2.25 on 2025-11-05 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0024_systemconfig_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'entreprise")),
                ('code', models.CharField(help_text="Code unique de l'entreprise", max_length=20, unique=True, verbose_name='Code entreprise')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('tax_id', models.CharField(blank=True, help_text="Numéro d'identification fiscale (ICE, SIREN, etc.)", max_length=50, verbose_name='Numéro fiscal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Entreprise active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(max_length=64, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('employee', 'Employé')], default='employee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text="Entreprise à laquelle l'utilisateur appartient", on_delete=django.db.models.deletion.CASCADE, related_name='users', to='API.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='achat',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cet achat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='API.company'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce bon de livraison', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='API.company'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cette catégorie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='API.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='API.company'),
        ),
        migrations.AddField(
            model_name='facture',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cette facture', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='API.company'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce fournisseur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='API.company'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Entreprise propriétaire de cette session d'inventaire", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='API.company'),
        ),
        migrations.AddField(
            model_name='produit',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce produit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='API.company'),
        ),
        migrations.AddField(
            model_name='vente',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cette vente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='API.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cet entrepôt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='API.company'),
        ),
        migrations.AlterUniqueTogether(
            name='bonlivraison',
            unique_together={('company', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('company', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('company', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorysession',
            unique_together={('company', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('company', 'reference'), ('company', 'code_barre')},
        ),
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('company', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
    ]
