# Generated by Django 4.2.25 on 2025-11-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_company_alter_bonlivraison_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('vehicule_type', models.CharField(blank=True, help_text='Ex: Camion, Camionnette, Moto', max_length=100, verbose_name='Type de véhicule')),
                ('vehicule_marque', models.CharField(blank=True, max_length=100, verbose_name='Marque du véhicule')),
                ('immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('capacite_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacité de charge (kg)')),
                ('numero_permis', models.CharField(blank=True, max_length=50, verbose_name='Numéro de permis')),
                ('date_expiration_permis', models.DateField(blank=True, null=True, verbose_name="Date d'expiration du permis")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_disponible', models.BooleanField(default=True, help_text='Indique si le livreur est disponible pour une tournée', verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient le livreur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to='API.company')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('company', 'telephone')},
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Généré automatiquement (ex: TOUR-20250107-001)', max_length=50, unique=True, verbose_name='Numéro de tournée')),
                ('date', models.DateField(verbose_name='Date de la tournée')),
                ('heure_depart_prevue', models.TimeField(verbose_name='Heure de départ prévue')),
                ('heure_depart_reelle', models.TimeField(blank=True, null=True, verbose_name='Heure de départ réelle')),
                ('heure_retour_prevue', models.TimeField(blank=True, null=True, verbose_name='Heure de retour prévue')),
                ('heure_retour_reelle', models.TimeField(blank=True, null=True, verbose_name='Heure de retour réelle')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance totale (km)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient la tournée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='API.company')),
                ('livreur', models.ForeignKey(blank=True, help_text='Livreur assigné à cette tournée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='API.livreur')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Entrepôt de départ de la tournée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='API.warehouse')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('company', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ArretLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(help_text='Ordre de passage (1, 2, 3...)', verbose_name='Ordre dans la tournée')),
                ('heure_prevue', models.TimeField(verbose_name='Heure prévue')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('adresse_livraison', models.TextField(help_text='Adresse complète de livraison', verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livre', 'Livré'), ('echec', 'Échec'), ('reporte', 'Reporté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('signature_client', models.TextField(blank=True, help_text='Signature électronique du client', verbose_name='Signature client (base64)')),
                ('nom_recepteur', models.CharField(blank=True, help_text='Nom de la personne qui a réceptionné', max_length=200, verbose_name='Nom du récepteur')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('raison_echec', models.TextField(blank=True, help_text="Si statut = échec, raison de l'échec", verbose_name="Raison de l'échec")),
                ('photo_livraison', models.TextField(blank=True, help_text='Photo de preuve de livraison', verbose_name='Photo de livraison (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_livraison', models.ForeignKey(blank=True, help_text='Bon de livraison associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrets_tournee', to='API.bonlivraison')),
                ('client', models.ForeignKey(help_text='Client destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='arrets_livraison', to='API.client')),
                ('company', models.ForeignKey(blank=True, help_text="Entreprise à laquelle appartient l'arrêt", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrets_livraison', to='API.company')),
                ('tournee', models.ForeignKey(help_text='Tournée à laquelle appartient cet arrêt', on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='API.tournee')),
                ('vente', models.ForeignKey(blank=True, help_text='Vente associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrets_tournee', to='API.vente')),
            ],
            options={
                'verbose_name': 'Arrêt de livraison',
                'verbose_name_plural': 'Arrêts de livraison',
                'ordering': ['tournee', 'ordre'],
                'unique_together': {('tournee', 'ordre')},
            },
        ),
    ]
