# Generated by Django 4.2.25 on 2025-11-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0027_arrettourneemobile_livreurdistribution_tourneemobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreurdistribution',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreur_distribution_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
