# Generated by Django 4.2.25 on 2025-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_alter_livreurdistribution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreurdistribution',
            name='clients_assignes',
            field=models.ManyToManyField(blank=True, help_text='Clients assignés à ce livreur pour les tournées', related_name='livreurs_assignes', to='API.client'),
        ),
    ]
