# Generated by Django 4.2.25 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_livreurdistribution_clients_assignes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneemobile',
            name='argent_depart',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant prédéfini donné au livreur en début de tournée', max_digits=12, verbose_name='Argent de départ'),
        ),
    ]
