# Generated by Django 4.2.25 on 2025-11-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0030_tourneemobile_argent_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de transfert')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('en_transit', 'En transit'), ('receptionne', 'Réceptionné'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce transfert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_stock', to='API.company')),
                ('demandeur', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_demandes', to=settings.AUTH_USER_MODEL)),
                ('entrepot_destination', models.ForeignKey(help_text='Entrepôt de destination (van ou autre entrepôt)', on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='API.warehouse')),
                ('entrepot_source', models.ForeignKey(help_text="Entrepôt d'origine", on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='API.warehouse')),
                ('recepteur', models.ForeignKey(blank=True, help_text='Utilisateur qui a réceptionné le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_receptionnes', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-date_creation', 'numero'],
                'unique_together': {('company', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LigneTransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité à transférer')),
                ('quantite_recue', models.PositiveIntegerField(blank=True, help_text='Quantité effectivement reçue (peut différer de la quantité envoyée)', null=True, verbose_name='Quantité reçue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('produit', models.ForeignKey(help_text='Produit à transférer', on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
                ('transfert', models.ForeignKey(help_text='Transfert parent', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.transfertstock')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
                'unique_together': {('transfert', 'produit')},
            },
        ),
    ]
