# Generated by Django 4.2.25 on 2025-11-19 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0031_add_transfert_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraisonVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Format: BL-VAN-YYYYMMDD-NNN (auto-généré)', max_length=50, unique=True, verbose_name='Numéro du bon')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('signature_client', models.TextField(blank=True, verbose_name='Signature client (base64)')),
                ('nom_recepteur', models.CharField(blank=True, max_length=100, verbose_name='Nom du récepteur')),
                ('photo_livraison', models.TextField(blank=True, verbose_name='Photo de livraison (base64)')),
                ('montant_total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total HT')),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total TTC')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('notes_livreur', models.TextField(blank=True, verbose_name='Notes du livreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arret', models.ForeignKey(blank=True, help_text='Arrêt de livraison associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='API.arrettourneemobile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_van', to='API.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_van_crees', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='API.livreurdistribution')),
                ('tournee', models.ForeignKey(help_text='Tournée associée au bon de livraison', on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='API.tourneemobile')),
            ],
            options={
                'verbose_name': 'Bon de livraison van',
                'verbose_name_plural': 'Bons de livraison vans',
                'ordering': ['-date_creation', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonLivraisonVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité livrée')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.bonlivraisonvan')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
            ],
            options={
                'verbose_name': 'Ligne bon livraison van',
                'verbose_name_plural': 'Lignes bons livraison vans',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='bonlivraisonvan',
            index=models.Index(fields=['numero'], name='API_bonlivr_numero_031340_idx'),
        ),
        migrations.AddIndex(
            model_name='bonlivraisonvan',
            index=models.Index(fields=['tournee', 'date_creation'], name='API_bonlivr_tournee_6de5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='bonlivraisonvan',
            index=models.Index(fields=['livreur', 'date_creation'], name='API_bonlivr_livreur_9866d2_idx'),
        ),
        migrations.AddIndex(
            model_name='bonlivraisonvan',
            index=models.Index(fields=['statut'], name='API_bonlivr_statut_cd7d99_idx'),
        ),
    ]
