# Generated by Django 4.2.25 on 2025-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_bonlivraisonvan_lignebonlivraisonvan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS', max_digits=10, null=True),
        ),
    ]
