# Generated by Django 4.2.25 on 2025-11-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_client_lat_client_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreurdistribution',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Position GPS actuelle du livreur', max_digits=10, null=True, verbose_name='Latitude actuelle'),
        ),
        migrations.AddField(
            model_name='livreurdistribution',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Position GPS actuelle du livreur', max_digits=10, null=True, verbose_name='Longitude actuelle'),
        ),
        migrations.AddField(
            model_name='livreurdistribution',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la dernière position GPS', null=True, verbose_name='Dernière mise à jour GPS'),
        ),
    ]
