# Generated by Django 4.2.25 on 2025-11-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_livreurdistribution_current_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcaissemobile',
            name='detail_billets_json',
            field=models.TextField(blank=True, help_text='Format: {"2000": 5, "1000": 10, "500": 3, ...}', verbose_name='Détail des billets (JSON)'),
        ),
    ]
