# Generated by Django 4.2.25 on 2025-11-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_add_detail_billets_to_rapport_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_souhaitee', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('montant_total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notes_preparation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('app_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='API.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_clients', to='API.company')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_prises', to='API.livreurdistribution')),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'db_table': 'distribution_commande_client',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='API.commandeclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'distribution_ligne_commande_client',
            },
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['company', 'statut'], name='distributio_company_adaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['livreur', 'date_commande'], name='distributio_livreur_75b8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['client', 'statut'], name='distributio_client__75b7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeclient',
            index=models.Index(fields=['app_id'], name='distributio_app_id_089c21_idx'),
        ),
    ]
