# Generated by Django 4.2.25 on 2025-11-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_commandeclient_lignecommandeclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignebonlivraisonvan',
            name='bon',
        ),
        migrations.RemoveField(
            model_name='lignebonlivraisonvan',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='rapportcaissemobile',
            name='detail_billets_json',
        ),
        migrations.AddField(
            model_name='arrettourneemobile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cet enregistrement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrets_tournees_mobiles', to='API.company'),
        ),
        migrations.AddField(
            model_name='ligneventetourneemobile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cet enregistrement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ventes_tournees_mobiles', to='API.company'),
        ),
        migrations.AddField(
            model_name='rapportcaissemobile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cet enregistrement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_caisses_mobiles', to='API.company'),
        ),
        migrations.AddField(
            model_name='tourneemobile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cet enregistrement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournees_mobiles', to='API.company'),
        ),
        migrations.AddField(
            model_name='ventetourneemobile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cet enregistrement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes_tournees_mobiles', to='API.company'),
        ),
        migrations.DeleteModel(
            name='BonLivraisonVan',
        ),
        migrations.DeleteModel(
            name='LigneBonLivraisonVan',
        ),
    ]
