# Generated by Django 4.2.25 on 2025-11-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_remove_lignebonlivraisonvan_bon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Entreprise - auto-assignée depuis le client si non fournie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_clients', to='API.company'),
        ),
    ]
