# Generated by Django 4.2.25 on 2025-11-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_allow_null_company_commandeclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventetourneemobile',
            name='arret',
            field=models.ForeignKey(blank=True, help_text='Arrêt associé (optionnel pour ventes directes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='API.arrettourneemobile'),
        ),
        migrations.AlterField(
            model_name='ventetourneemobile',
            name='numero_vente',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° Vente'),
        ),
        migrations.AlterField(
            model_name='ventetourneemobile',
            name='tournee',
            field=models.ForeignKey(blank=True, help_text='Tournée associée (optionnel pour ventes directes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='API.tourneemobile'),
        ),
    ]
