# Generated by Django 4.2.25 on 2025-11-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0039_allow_vente_without_tournee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Fournisseur principal du produit (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité initiale en stock (optionnel)', verbose_name='Quantité en stock'),
        ),
    ]
