# Generated by Django 4.2.25 on 2025-11-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_make_fournisseur_quantite_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='type_prix',
            field=models.ForeignKey(blank=True, help_text='Type de prix à utiliser pour les ventes (Détail, Supérette, Gros, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='API.typeprix'),
        ),
    ]
