# Generated by Django 4.2.25 on 2025-11-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_add_type_prix_to_tournee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneemobile',
            name='type_prix',
            field=models.ForeignKey(blank=True, help_text='Type de prix à utiliser pour les ventes (Détail, Supérette, Gros)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees_mobiles', to='API.typeprix'),
        ),
    ]
