# Generated by Django 4.2.25 on 2025-11-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0042_add_type_prix_to_tourneemobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique (ex: STANDARD, AID, RAMADAN)', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Libellé du code de prix', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du code de prix')),
                ('date_debut', models.DateField(blank=True, help_text='Date de début de validité', null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de validité', null=True, verbose_name='Date fin')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_default', models.BooleanField(default=False, help_text='Code de prix par défaut')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code de prix',
                'verbose_name_plural': 'Codes de prix',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='prixproduit',
            options={'ordering': ['produit', 'code_prix__ordre', 'type_prix__ordre'], 'verbose_name': 'Prix produit', 'verbose_name_plural': 'Prix produits'},
        ),
        migrations.RemoveField(
            model_name='tournee',
            name='type_prix',
        ),
        migrations.RemoveField(
            model_name='tourneemobile',
            name='type_prix',
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Montant du prix pour cette combinaison', max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='type_prix',
            field=models.ForeignKey(help_text='Type de client (Détail, Supérette, Gros)', on_delete=django.db.models.deletion.PROTECT, related_name='prix', to='API.typeprix'),
        ),
        migrations.AlterField(
            model_name='typeprix',
            name='code',
            field=models.CharField(choices=[('DETAIL', 'Détail'), ('SUPERETTE', 'Supérette'), ('GROS', 'Gros')], help_text='Type de client (DETAIL, SUPERETTE, GROS)', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='prixproduit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prixproduit',
            name='code_prix',
            field=models.ForeignKey(blank=True, help_text='Code de prix (STANDARD, AID, RAMADAN, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prix', to='API.codeprix'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='code_prix',
            field=models.ForeignKey(blank=True, help_text='Code de prix à utiliser pour les ventes (STANDARD, AID, RAMADAN, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='API.codeprix'),
        ),
        migrations.AddField(
            model_name='tourneemobile',
            name='code_prix',
            field=models.ForeignKey(blank=True, help_text='Code de prix à utiliser pour les ventes (STANDARD, AID, RAMADAN, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees_mobiles', to='API.codeprix'),
        ),
        migrations.AlterUniqueTogether(
            name='prixproduit',
            unique_together={('produit', 'code_prix', 'type_prix')},
        ),
        migrations.RemoveField(
            model_name='prixproduit',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='prixproduit',
            name='date_fin',
        ),
    ]
