# Generated by Django 4.2.25 on 2025-11-25 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0043_restructure_prix_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], help_text='1=Lundi, 7=Dimanche', verbose_name='Jour de la semaine')),
                ('is_active', models.BooleanField(default=True, help_text='Si inactif, les tournées ne seront pas générées automatiquement', verbose_name='Actif')),
                ('date_debut', models.DateField(blank=True, help_text="Date à partir de laquelle le planning s'applique", null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date jusqu'à laquelle le planning s'applique", null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_prix', models.ForeignKey(blank=True, help_text='Code prix à appliquer pour cette tournée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings_hebdo', to='API.codeprix')),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient ce planning', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannings_hebdo', to='API.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings_hebdo_crees', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_hebdo', to='API.livreurdistribution')),
            ],
            options={
                'verbose_name': 'Planning hebdomadaire',
                'verbose_name_plural': 'Plannings hebdomadaires',
                'ordering': ['livreur', 'jour_semaine'],
                'indexes': [models.Index(fields=['livreur', 'jour_semaine'], name='API_plannin_livreur_8b9719_idx'), models.Index(fields=['company', 'is_active'], name='API_plannin_company_53799b_idx')],
                'unique_together': {('livreur', 'jour_semaine', 'company')},
            },
        ),
    ]
