# Generated by Django 4.2.25 on 2025-11-25 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0044_add_planning_hebdomadaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLivreurHebdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], help_text='1=Lundi, 7=Dimanche', verbose_name='Jour de la semaine')),
                ('ordre_passage', models.PositiveIntegerField(blank=True, help_text='Ordre de visite du client dans la tournée', null=True, verbose_name='Ordre de passage')),
                ('is_active', models.BooleanField(default=True, help_text='Si inactif, cette configuration ne sera pas utilisée', verbose_name='Actif')),
                ('date_debut', models.DateField(blank=True, help_text="Date à partir de laquelle cette configuration s'applique", null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date jusqu'à laquelle cette configuration s'applique", null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreurs_hebdo', to='API.client')),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cette configuration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_livreurs_hebdo', to='API.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_clients_livreurs_creees', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_hebdo', to='API.livreurdistribution')),
            ],
            options={
                'verbose_name': 'Configuration Client-Livreur Hebdomadaire',
                'verbose_name_plural': 'Configurations Clients-Livreurs Hebdomadaires',
                'ordering': ['livreur', 'jour_semaine', 'ordre_passage'],
                'indexes': [models.Index(fields=['livreur', 'jour_semaine', 'is_active'], name='API_clientl_livreur_0779cb_idx'), models.Index(fields=['client', 'jour_semaine'], name='API_clientl_client__8d5524_idx'), models.Index(fields=['company', 'is_active'], name='API_clientl_company_7bb772_idx')],
                'unique_together': {('client', 'jour_semaine', 'company')},
            },
        ),
    ]
