# Generated by Django 4.2.25 on 2025-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0045_add_client_livreur_hebdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_caisse', 'Peut accéder à la caisse'), ('view_ventes', 'Peut voir les ventes'), ('create_vente', 'Peut créer des ventes'), ('view_stock_management', 'Peut voir la gestion des stocks'), ('view_stock_dashboard', 'Peut voir le tableau de bord des stocks'), ('manage_transferts', 'Peut gérer les transferts'), ('charger_van', 'Peut charger les vans'), ('view_distribution', 'Peut voir le module distribution'), ('view_stats_livreurs', 'Peut voir les statistiques livreurs'), ('manage_tournees', 'Peut gérer les tournées'), ('manage_livreurs', 'Peut gérer les livreurs'), ('view_parametres', 'Peut voir les paramètres'), ('manage_clients', 'Peut gérer les clients'), ('manage_fournisseurs', 'Peut gérer les fournisseurs'), ('manage_categories', 'Peut gérer les catégories'), ('manage_entrepots', 'Peut gérer les entrepôts'), ('view_rapports', 'Peut voir les rapports'), ('view_statistiques', 'Peut voir les statistiques'), ('export_data', 'Peut exporter les données'), ('view_admin', "Peut voir l'administration"), ('manage_users', 'Peut gérer les utilisateurs'), ('manage_roles', 'Peut gérer les rôles')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
