# Generated by Django 4.2.25 on 2025-11-27 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0047_add_distribution_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(default=django.utils.timezone.now, verbose_name='Date de visite')),
                ('heure_visite', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de visite')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('resultat', models.CharField(choices=[('vente', 'Vente effectuée'), ('commande', 'Commande prise'), ('absent', 'Client absent'), ('ferme', 'Établissement fermé'), ('refuse', 'Client a refusé'), ('autre', 'Autre')], default='vente', max_length=20, verbose_name='Résultat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('app_id', models.CharField(blank=True, help_text="ID unique depuis l'app mobile pour éviter les doublons", max_length=200, null=True, unique=True, verbose_name='ID App Mobile')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Date synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='API.client')),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient cette visite', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visites_clients', to='API.company')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_effectuees', to='API.livreurdistribution')),
                ('tournee', models.ForeignKey(blank=True, help_text='Tournée durant laquelle la visite a été effectuée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites', to='API.tourneemobile')),
            ],
            options={
                'verbose_name': 'Visite client',
                'verbose_name_plural': 'Visites clients',
                'db_table': 'distribution_visite_client',
                'ordering': ['-date_visite', '-heure_visite'],
                'indexes': [models.Index(fields=['company', 'date_visite'], name='distributio_company_3fc854_idx'), models.Index(fields=['livreur', 'date_visite'], name='distributio_livreur_ed0775_idx'), models.Index(fields=['client', 'date_visite'], name='distributio_client__5158fa_idx'), models.Index(fields=['app_id'], name='distributio_app_id_d058fe_idx')],
            },
        ),
    ]
