# Generated by Django 4.2.25 on 2025-12-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0048_add_visite_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique de la promotion (ex: PROMO-NOEL-2024)', max_length=50, unique=True, verbose_name='Code promotion')),
                ('nom', models.CharField(help_text='Nom descriptif de la promotion', max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la promotion', verbose_name='Description')),
                ('type_promotion', models.CharField(choices=[('pourcentage', 'Réduction en pourcentage'), ('valeur_fixe', 'Réduction valeur fixe'), ('prix_special', 'Prix spécial'), ('achetez_x_payez_y', 'Achetez X, payez Y'), ('achetez_x_offert_y', 'Achetez X, Y offert(s)'), ('lot', 'Promotion lot'), ('demunerisation', 'Prix de démunération'), ('quantite', 'Réduction par quantité')], default='pourcentage', max_length=30, verbose_name='Type de promotion')),
                ('valeur_pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de réduction (ex: 10 pour 10%)', max_digits=5, null=True, verbose_name='Pourcentage de réduction')),
                ('valeur_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe de réduction (ex: 2.00 €)', max_digits=10, null=True, verbose_name='Montant de réduction fixe')),
                ('prix_special', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécial fixe à appliquer', max_digits=10, null=True, verbose_name='Prix spécial')),
                ('quantite_achat', models.PositiveIntegerField(blank=True, help_text="Nombre de produits à acheter pour déclencher l'offre", null=True, verbose_name='Quantité à acheter')),
                ('quantite_offerte', models.PositiveIntegerField(blank=True, help_text='Nombre de produits offerts ou nombre à payer', null=True, verbose_name='Quantité offerte/payée')),
                ('unite_application', models.CharField(choices=[('unite', 'Par unité'), ('carton', 'Par carton'), ('colis', 'Par colis'), ('palette', 'Par palette')], default='unite', help_text="Unité sur laquelle la promotion s'applique", max_length=20, verbose_name="S'applique sur")),
                ('date_debut', models.DateTimeField(help_text='Date et heure de début de la promotion', verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(help_text='Date et heure de fin de la promotion', verbose_name='Date de fin')),
                ('quantite_minimum', models.PositiveIntegerField(default=1, help_text='Quantité minimum pour activer la promotion', verbose_name='Quantité minimum')),
                ('quantite_maximum', models.PositiveIntegerField(blank=True, help_text='Quantité maximum bénéficiant de la promotion (optionnel)', null=True, verbose_name='Quantité maximum')),
                ('conditionnement_minimum', models.CharField(choices=[('unite', 'Par unité'), ('carton', 'Par carton'), ('colis', 'Par colis'), ('palette', 'Par palette')], default='unite', help_text='Conditionnement minimum requis pour la promotion', max_length=20, verbose_name='Conditionnement minimum')),
                ('carton_complet_requis', models.BooleanField(default=False, help_text="La promotion nécessite l'achat de cartons complets", verbose_name='Carton complet requis')),
                ('est_cumulable', models.BooleanField(default=False, help_text="Peut être cumulée avec d'autres promotions", verbose_name='Cumulable avec autres promotions')),
                ('priorite', models.IntegerField(default=0, help_text="Priorité d'application (plus élevé = prioritaire)", verbose_name='Priorité')),
                ('usage_maximum', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations (optionnel)", null=True, verbose_name='Usage maximum')),
                ('usage_par_client', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations par client (optionnel)", null=True, verbose_name='Usage par client')),
                ('usage_actuel', models.PositiveIntegerField(default=0, help_text="Nombre d'utilisations de cette promotion", verbose_name='Utilisations actuelles')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('planifiee', 'Planifiée'), ('expiree', 'Expirée'), ('suspendue', 'Suspendue')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, help_text='Catégorie de produits (optionnel si produit sélectionné)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='API.categorie')),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise propriétaire de cette promotion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='API.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_creees', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, help_text='Devise pour les montants de la promotion', null=True, on_delete=django.db.models.deletion.PROTECT, to='API.currency')),
                ('produit', models.ForeignKey(blank=True, help_text='Produit spécifique (optionnel si catégorie sélectionnée)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='API.produit')),
                ('types_prix_eligibles', models.ManyToManyField(blank=True, help_text='Types de clients éligibles (vide = tous)', related_name='promotions', to='API.typeprix')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priorite', '-created_at'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AlterModelOptions(
            name='pagepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_caisse', 'Peut accéder à la caisse'), ('view_ventes', 'Peut voir les ventes'), ('create_vente', 'Peut créer des ventes'), ('view_stock_management', 'Peut voir la gestion des stocks'), ('view_stock_dashboard', 'Peut voir le tableau de bord des stocks'), ('manage_transferts', 'Peut gérer les transferts'), ('charger_van', 'Peut charger les vans'), ('view_distribution', 'Peut voir le module distribution'), ('view_livreurs', 'Peut voir les livreurs'), ('manage_livreurs', 'Peut gérer les livreurs'), ('view_tournees', 'Peut voir les tournées'), ('manage_tournees', 'Peut gérer les tournées'), ('view_commandes_mobile', 'Peut voir les commandes mobile'), ('view_distribution_dashboard', 'Peut voir le tableau de bord distribution'), ('view_config_clients_chauffeurs', 'Peut voir la config clients/chauffeurs'), ('manage_config_clients_chauffeurs', 'Peut gérer la config clients/chauffeurs'), ('view_stats_livreurs', 'Peut voir les statistiques livreurs'), ('view_app_mobile_livreurs', "Peut accéder à l'app mobile livreurs"), ('view_carte_gps_livreurs', 'Peut voir la carte GPS livreurs'), ('view_parametres', 'Peut voir les paramètres'), ('manage_clients', 'Peut gérer les clients'), ('manage_fournisseurs', 'Peut gérer les fournisseurs'), ('manage_categories', 'Peut gérer les catégories'), ('manage_entrepots', 'Peut gérer les entrepôts'), ('view_rapports', 'Peut voir les rapports'), ('view_statistiques', 'Peut voir les statistiques'), ('export_data', 'Peut exporter les données'), ('view_admin', "Peut voir l'administration"), ('manage_users', 'Peut gérer les utilisateurs'), ('manage_roles', 'Peut gérer les rôles'), ('view_promotions', 'Peut voir les promotions'), ('manage_promotions', 'Peut gérer les promotions')]},
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('montant_economise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Économie réalisée')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_utilisees', to='API.client')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='API.promotion')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_appliquees', to='API.vente')),
            ],
            options={
                'verbose_name': 'Utilisation promotion',
                'verbose_name_plural': 'Utilisations promotions',
                'ordering': ['-date_utilisation'],
            },
        ),
        migrations.CreateModel(
            name='Conditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unites_par_carton', models.PositiveIntegerField(default=1, help_text="Nombre d'unités dans un carton", verbose_name='Unités par carton')),
                ('prix_carton', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du carton complet (optionnel, sinon calculé automatiquement)', max_digits=10, null=True, verbose_name='Prix du carton')),
                ('cartons_par_colis', models.PositiveIntegerField(default=1, help_text='Nombre de cartons dans un colis', verbose_name='Cartons par colis')),
                ('prix_colis', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du colis complet (optionnel)', max_digits=10, null=True, verbose_name='Prix du colis')),
                ('colis_par_palette', models.PositiveIntegerField(blank=True, help_text='Nombre de colis dans une palette (optionnel)', null=True, verbose_name='Colis par palette')),
                ('prix_palette', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de la palette complète (optionnel)', max_digits=12, null=True, verbose_name='Prix de la palette')),
                ('prix_demunerisation', models.DecimalField(blank=True, decimal_places=2, help_text="Prix spécial pour vente à l'unité depuis carton ouvert", max_digits=10, null=True, verbose_name='Prix de démunération')),
                ('poids_carton', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids du carton (kg)')),
                ('dimensions_carton', models.CharField(blank=True, max_length=50, verbose_name='Dimensions carton (LxlxH cm)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(help_text='Produit concerné', on_delete=django.db.models.deletion.CASCADE, related_name='conditionnements', to='API.produit')),
            ],
            options={
                'verbose_name': 'Conditionnement',
                'verbose_name_plural': 'Conditionnements',
                'ordering': ['produit__designation'],
            },
        ),
    ]
