# Generated by Django 4.2.25 on 2025-12-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0049_add_promotions_and_conditionnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du secteur (ex: SEC001)', max_length=20)),
                ('nom', models.CharField(help_text='Nom du secteur', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du secteur', null=True)),
                ('couleur', models.CharField(default='#3498db', help_text="Couleur d'affichage (hex)", max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Secteur actif ou non')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise propriétaire de ce secteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='API.company')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['nom'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
