# Generated by Django 4.2.25 on 2025-12-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0050_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secteur',
            field=models.ForeignKey(blank=True, help_text='Secteur géographique/commercial du client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='API.secteur'),
        ),
    ]
