# Generated by Django 4.2.25 on 2025-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0052_add_assignation_config_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ai',
            field=models.CharField(blank=True, help_text="Article d'Imposition", max_length=20, verbose_name="AI (Article d'Imposition)"),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=20, verbose_name="NIF (Numéro d'Identification Fiscale)"),
        ),
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=20, verbose_name="NIS (Numéro d'Identification Statistique)"),
        ),
        migrations.AddField(
            model_name='client',
            name='rc',
            field=models.CharField(blank=True, help_text='Numéro du Registre de Commerce', max_length=20, verbose_name='RC (Registre de Commerce)'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ai',
            field=models.CharField(blank=True, help_text="Article d'Imposition", max_length=20, verbose_name="AI (Article d'Imposition)"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=20, verbose_name="NIF (Numéro d'Identification Fiscale)"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nis',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=20, verbose_name="NIS (Numéro d'Identification Statistique)"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='rc',
            field=models.CharField(blank=True, help_text='Numéro du Registre de Commerce', max_length=20, verbose_name='RC (Registre de Commerce)'),
        ),
    ]
