# Generated by Django 4.2.25 on 2025-12-03 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0053_client_ai_client_nif_client_nis_client_rc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(help_text='Symbole (ex: $, DA, DH)', max_length=5),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valeur_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe de réduction (ex: 2.00 DA)', max_digits=10, null=True, verbose_name='Montant de réduction fixe'),
        ),
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, help_text='Date du paiement')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant payé', max_digits=12)),
                ('moyen_paiement', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Numéro de chèque, référence de virement, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='API.vente')),
            ],
            options={
                'verbose_name': 'Paiement de vente',
                'verbose_name_plural': 'Paiements de ventes',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
