# Generated by Django 4.2.25 on 2025-12-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0054_alter_currency_symbol_alter_promotion_valeur_fixe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='prix_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire avant application de la promotion', max_digits=10, null=True, verbose_name='Prix original (avant promo)'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Promotion appliquée à cette ligne', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_vente', to='API.promotion'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='quantite_offerte',
            field=models.PositiveIntegerField(default=0, help_text='Quantité offerte gratuitement (pour promos X+Y)', verbose_name='Quantité offerte'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='remise_promo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la remise appliquée par la promotion', max_digits=10, verbose_name='Remise promotion'),
        ),
    ]
