# Generated by Django 4.2.25 on 2025-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0055_add_promotion_to_lignevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='pieces_par_carton',
            field=models.IntegerField(default=1, help_text='Nombre de pièces contenues dans un carton', verbose_name='Pièces par carton'),
        ),
        migrations.AddField(
            model_name='achat',
            name='unite_achat',
            field=models.CharField(choices=[('piece', 'Pièce'), ('carton', 'Carton')], default='piece', help_text="Unité d'achat: pièce ou carton", max_length=10, verbose_name="Unité d'achat"),
        ),
    ]
