# Generated by Django 4.2.25 on 2025-12-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0056_achat_pieces_par_carton_achat_unite_achat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournee',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('edit_tournee_en_cours', 'Peut modifier une tournée en cours')], 'verbose_name': 'Tournée', 'verbose_name_plural': 'Tournées'},
        ),
    ]
