# Generated by Django 4.2.25 on 2025-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0057_add_edit_tournee_en_cours_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportcaissemobile',
            name='detail_billets',
            field=models.JSONField(blank=True, help_text='Détail des billets et pièces retournés: {"2000": 5, "1000": 3, "500": 10, ...}', null=True, verbose_name='Détail des billets'),
        ),
    ]
