# Generated by Django 4.2.25 on 2025-12-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0059_remove_old_detail_billets_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_prix',
            field=models.ForeignKey(blank=True, help_text='Type de prix appliqué à ce client (Détail, Supérette, Gros)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='API.typeprix'),
        ),
    ]
