# Generated by Django 4.2.25 on 2025-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0060_client_type_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeprix',
            name='code',
            field=models.CharField(help_text='Code du type de prix (ex: DETAIL, SUPERETTE, GROS)', max_length=20, unique=True),
        ),
    ]
