# Generated by Django 4.2.25 on 2025-12-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0061_remove_typeprix_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code_prix',
            field=models.ForeignKey(blank=True, help_text='Code de prix (période) auquel cette promotion est liée (ex: RAMADAN, STANDARD)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_detail', to='API.codeprix'),
        ),
    ]
