# Generated by Django 4.2.25 on 2025-12-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0062_promotion_code_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='entrepot',
            field=models.ForeignKey(blank=True, help_text='Entrepôt mobile (van) assigné à ce livreur pour gérer son stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs_assignes', to='API.warehouse', verbose_name='Van/Entrepôt assigné'),
        ),
    ]
