# Generated by Django 4.2.25 on 2025-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0063_livreur_entrepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='date_paiement',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le paiement a été effectué', null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='est_paye',
            field=models.BooleanField(default=False, help_text='Indique si la commande a été payée', verbose_name='Est payé'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà payé (peut être partiel)', max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='type_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('credit', 'À crédit'), ('virement', 'Virement'), ('non_paye', 'Non payé')], default='non_paye', help_text='Mode de paiement utilisé', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
