# Generated by Django 4.2.25 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0064_commandeclient_date_paiement_commandeclient_est_paye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
