# Generated by Django 4.2.25 on 2026-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0065_alter_lignecommandeclient_taux_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
    ]
