# Generated by Django 4.2.25 on 2026-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0066_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit (max 2 MB, sera compressée automatiquement)', null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
