# Generated by Django 4.2.25 on 2026-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0067_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(blank=True, help_text='Identifiant unique permanent (généré automatiquement si vide)', null=True, unique=True, verbose_name='UUID permanent'),
        ),
    ]
