# Generated by Django 4.2.25 on 2026-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0068_add_uuid_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Solde initial du client (positif = crédit accordé, négatif = dette). Indépendant des paiements partiels sur ventes.', max_digits=12, null=True, verbose_name='Solde du compte'),
        ),
    ]
