# Generated by Django 4.2.25 on 2026-01-18 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0069_add_solde_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du paiement', max_digits=12, verbose_name='Montant payé')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, help_text='Date et heure du paiement', verbose_name='Date du paiement')),
                ('solde_avant', models.DecimalField(decimal_places=2, help_text='Solde du client avant ce paiement', max_digits=12, verbose_name='Solde avant paiement')),
                ('solde_apres', models.DecimalField(decimal_places=2, help_text='Solde du client après ce paiement', max_digits=12, verbose_name='Solde après paiement')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur ce paiement', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client ayant effectué le paiement', on_delete=django.db.models.deletion.CASCADE, related_name='paiements_solde', to='API.client')),
                ('company', models.ForeignKey(blank=True, help_text='Entreprise à laquelle appartient ce paiement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_solde', to='API.company')),
                ('enregistre_par', models.ForeignKey(blank=True, help_text='Utilisateur ayant enregistré ce paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_solde_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement de solde',
                'verbose_name_plural': 'Paiements de solde',
                'ordering': ['-date_paiement'],
                'indexes': [models.Index(fields=['client', '-date_paiement'], name='API_paiemen_client__55934e_idx'), models.Index(fields=['company', '-date_paiement'], name='API_paiemen_company_b58d00_idx')],
            },
        ),
    ]
