# Generated by Django 4.2.25 on 2026-05-10 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0071_add_stock_non_negative_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventetourneemobile',
            name='bon_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_mobiles', to='API.bonlivraison'),
        ),
    ]
