# Generated by Django 4.2.25 on 2026-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0072_add_bon_livraison_to_vente_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit (sera compressée automatiquement ; taille max : PRODUIT_IMAGE_MAX_SIZE_MB dans settings.py)', null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
