# Generated by Django 4.2.25 on 2026-09-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0073_produit_image_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='entrepot_rattachement',
            field=models.ForeignKey(blank=True, help_text='Entrepôt (gamme) auquel ce produit est rattaché pour les objectifs des vendeurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_rattaches', to='API.warehouse', verbose_name='Entrepôt / gamme de rattachement'),
        ),
        migrations.CreateModel(
            name='ObjectifVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('type_perimetre', models.CharField(choices=[('entrepot', 'Entrepôt / gamme'), ('categorie', 'Type de produit')], max_length=20, verbose_name='Périmètre')),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objectif de CA (TTC)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_vendeurs', to='API.categorie', verbose_name='Type de produit')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_vendeurs', to='API.company')),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_vendeurs', to='API.warehouse', verbose_name='Entrepôt / gamme')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='API.livreurdistribution', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Objectif vendeur',
                'verbose_name_plural': 'Objectifs vendeurs',
                'ordering': ['-annee', '-mois', 'livreur__nom', 'type_perimetre'],
            },
        ),
        migrations.AddConstraint(
            model_name='objectifvendeur',
            constraint=models.UniqueConstraint(condition=models.Q(('type_perimetre', 'entrepot')), fields=('livreur', 'annee', 'mois', 'entrepot'), name='objectif_vendeur_unique_entrepot_mois'),
        ),
        migrations.AddConstraint(
            model_name='objectifvendeur',
            constraint=models.UniqueConstraint(condition=models.Q(('type_perimetre', 'categorie')), fields=('livreur', 'annee', 'mois', 'categorie'), name='objectif_vendeur_unique_categorie_mois'),
        ),
        migrations.AddConstraint(
            model_name='objectifvendeur',
            constraint=models.CheckConstraint(check=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='objectif_vendeur_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='objectifvendeur',
            constraint=models.CheckConstraint(check=models.Q(('montant_objectif__gte', 0)), name='objectif_vendeur_montant_positif'),
        ),
    ]
